#!/usr/bin/env node
/**
 * Setup Environment Script
 * Copies environment variables from root .env.example to each service
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SERVICES_DIR = path.join(ROOT, 'services');

const services = [
    'auth-service',
    'qr-service',
    'redirect-service',
    'payment-service'
];

// Common env variables for all services
const commonEnv = `# Environment variables (auto-generated by setup script)
NODE_ENV=development

# Database (PostgreSQL)
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/qrcode_shiba?schema=public

# Redis
REDIS_URL=redis://localhost:6379
`;

// Service-specific configs
const serviceConfigs = {
    'auth-service': `PORT=3001

# JWT Secrets (change in production!)
JWT_ACCESS_SECRET=qrcode-shiba-access-secret-dev-2026
JWT_REFRESH_SECRET=qrcode-shiba-refresh-secret-dev-2026

# OAuth (Google)
GOOGLE_CLIENT_ID=your-google-client-id
GOOGLE_CLIENT_SECRET=your-google-client-secret
GOOGLE_CALLBACK_URL=http://localhost:3000/api/auth/google/callback
`,
    'qr-service': `PORT=3002

# AWS S3 (for file uploads)
AWS_ACCESS_KEY_ID=your-aws-access-key
AWS_SECRET_ACCESS_KEY=your-aws-secret-key
AWS_S3_BUCKET=qrcode-shiba-uploads
AWS_REGION=ap-southeast-1
`,
    'redirect-service': `PORT=3003

# Frontend URL for fallback redirects
FRONTEND_URL=http://localhost:3000
`,
    'payment-service': `PORT=3004

# Frontend URL
FRONTEND_URL=http://localhost:3000

# VNPay
VNPAY_TMN_CODE=your-vnpay-terminal-code
VNPAY_HASH_SECRET=your-vnpay-hash-secret
VNPAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
VNPAY_RETURN_URL=http://localhost:3000/payment/callback

# MoMo
MOMO_PARTNER_CODE=your-momo-partner-code
MOMO_ACCESS_KEY=your-momo-access-key
MOMO_SECRET_KEY=your-momo-secret-key
`
};

console.log('🔧 Setting up environment files...\n');

services.forEach(service => {
    const envPath = path.join(SERVICES_DIR, service, '.env');

    if (fs.existsSync(envPath)) {
        console.log(`⏭️  ${service}/.env already exists, skipping`);
        return;
    }

    const content = commonEnv + (serviceConfigs[service] || `PORT=3000\n`);
    fs.writeFileSync(envPath, content);
    console.log(`✅ Created ${service}/.env`);
});

console.log('\n🎉 Environment setup complete!');
console.log('\nNext steps:');
console.log('  1. Update the .env files with your actual credentials');
console.log('  2. Run: pnpm docker:up (start PostgreSQL & Redis)');
console.log('  3. Run: pnpm db:push (create database tables)');
console.log('  4. Run: pnpm dev (start all services)');
